name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22'

jobs:
  # ===========================================
  # Lint
  # ===========================================
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: bun-lint-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: bun-lint-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Type Check
  # ===========================================
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: bun-typecheck-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun typecheck

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: bun-typecheck-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Build
  # ===========================================
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: bun-build-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: bun-build-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Test (Intellitester)
  # ===========================================
  test-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Run Intellitester
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/intellitester@main
        with:
          test-file: tests/
          preview: 'false'
          working-directory: '.'
          node-version: ${{ env.NODE_VERSION }}
          package-manager: 'bun'
          browser: 'chrome'
          playwright-browsers: 'chromium'
          npm-registry: 'https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/'
          npm-token: ${{ secrets.FORGEJO_ACTIONS_TOKEN }}

  test-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Run Intellitester
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/intellitester@main
        with:
          test-file: tests/
          preview: 'false'
          working-directory: '.'
          node-version: ${{ env.NODE_VERSION }}
          package-manager: 'bun'
          browser: 'firefox'
          playwright-browsers: 'firefox'
          npm-registry: 'https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/'
          npm-token: ${{ secrets.FORGEJO_ACTIONS_TOKEN }}

  test-safari:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc

      - name: Run Intellitester
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/intellitester@main
        with:
          test-file: tests/
          preview: 'false'
          working-directory: '.'
          node-version: ${{ env.NODE_VERSION }}
          package-manager: 'bun'
          browser: 'safari'
          playwright-browsers: 'webkit'
          npm-registry: 'https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/'
          npm-token: ${{ secrets.FORGEJO_ACTIONS_TOKEN }}

  # ===========================================
  # Trigger Publish Workflow (tags only)
  # ===========================================
  trigger-publish:
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build, test-chromium, test-firefox, test-safari]
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push'
    steps:
      - name: Trigger publish workflow
        run: |
          VERSION="${{ github.ref_name }}"
          echo "Triggering publish workflow for version: ${VERSION}"

          curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://forge.blackleafdigital.com/api/v1/repos/${{ github.repository }}/actions/workflows/publish.yaml/dispatches" \
            -d "{\"ref\": \"main\", \"inputs\": {\"version\": \"${VERSION}\"}}"

          echo "Publish workflow triggered successfully"

  # ===========================================
  # Cache Cleanup
  # ===========================================
  cache-cleanup:
    name: Cleanup Old Caches
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build, test-chromium, test-firefox, test-safari]
    if: always()
    steps:
      - name: Cleanup old caches
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: cleanup
          max-age-days: '30'
          keep-latest: '5'
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}
