name: Publish NPM Package

on:
  # Only manual/API trigger - CI will call this after success on tags
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (no actual publish)'
        required: false
        default: false
        type: boolean

concurrency:
  group: publish-package
  cancel-in-progress: false

env:
  NODE_VERSION: '22'

jobs:
  # ===========================================
  # Determine Version
  # ===========================================
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Determine version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          if [ -z "$VERSION" ]; then
            echo "ERROR: No version provided"
            exit 1
          fi
          # Remove 'v' prefix if present
          TAG="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Building release: ${VERSION} (tag: ${TAG})"

  # ===========================================
  # Build and Publish to npm Registry
  # ===========================================
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure npm auth
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" >> ~/.npmrc

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: bun-publish-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Copy README to package
        run: cp README.md packages/amplify-astro-adapter/

      - name: Update version in package.json
        working-directory: packages/amplify-astro-adapter
        run: |
          VERSION="${{ needs.version.outputs.tag }}"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Update package version (skip if already matches)
          if [ "$CURRENT_VERSION" != "$VERSION" ]; then
            # Use node to update version (npm version doesn't work with workspace protocol)
            node -e "const pkg = require('./package.json'); pkg.version = '${VERSION}'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n')"
          fi

      - name: Publish to registry
        if: ${{ inputs.dry_run != 'true' }}
        working-directory: packages/amplify-astro-adapter
        run: |
          # Publish package
          npm publish --access public

      - name: Publish Dry Run
        if: ${{ inputs.dry_run == 'true' }}
        working-directory: packages/amplify-astro-adapter
        run: |
          echo "DRY RUN - Would publish amplify-astro-adapter@${{ needs.version.outputs.tag }}"

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: bun-publish-${{ hashFiles('**/bun.lockb') }}
          path: ~/.bun/install/cache
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Create Forgejo Release
  # ===========================================
  create-release:
    name: Create Forgejo Release
    runs-on: ubuntu-latest
    needs: [version, publish-npm]
    if: ${{ inputs.dry_run != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          VERSION="${{ needs.version.outputs.version }}"

          # Get commits since last tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Save to file for multiline handling
          cat > /tmp/changelog.txt << EOF
          ## amplify-astro-adapter ${{ needs.version.outputs.version }}

          ### Changes
          ${COMMITS}

          ### Installation

          \`\`\`bash
          npm install amplify-astro-adapter@${{ needs.version.outputs.tag }}
          \`\`\`

          \`\`\`bash
          pnpm add amplify-astro-adapter@${{ needs.version.outputs.tag }}
          \`\`\`

          \`\`\`bash
          yarn add amplify-astro-adapter@${{ needs.version.outputs.tag }}
          \`\`\`

          ### Package Published
          - amplify-astro-adapter@${{ needs.version.outputs.tag }}

          Published to: https://www.npmjs.com/package/amplify-astro-adapter
          EOF

      - name: Create Forgejo Release
        run: |
          VERSION="${{ needs.version.outputs.version }}"
          TAG="${{ needs.version.outputs.tag }}"

          # Read changelog
          BODY=$(cat /tmp/changelog.txt)

          # Determine if prerelease
          PRERELEASE="false"
          if echo "${VERSION}" | grep -qE '(alpha|beta|rc)'; then
            PRERELEASE="true"
          fi

          # Create release via Forgejo API
          RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://forge.blackleafdigital.com/api/v1/repos/${{ github.repository }}/releases" \
            -d "{
              \"tag_name\": \"${VERSION}\",
              \"name\": \"amplify-astro-adapter ${VERSION}\",
              \"body\": $(echo "$BODY" | jq -Rs .),
              \"draft\": false,
              \"prerelease\": ${PRERELEASE}
            }")

          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')

          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "ERROR: Failed to create release"
            echo "$RESPONSE" | jq .
            exit 1
          fi

          echo "Created release ID: $RELEASE_ID"
          echo "Release URL: https://forge.blackleafdigital.com/${{ github.repository }}/releases/tag/${VERSION}"

  # ===========================================
  # Trigger GitHub Release (Mirror)
  # ===========================================
  trigger-github-release:
    name: Trigger GitHub Release
    runs-on: ubuntu-latest
    needs: [version, create-release]
    if: ${{ inputs.dry_run != 'true' }}
    steps:
      - name: Trigger GitHub workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_ACCESS_TOKEN }}" \
            "https://api.github.com/repos/zachhandley/amplify-astro-adapter/actions/workflows/release.yaml/dispatches" \
            -d '{"ref":"main","inputs":{"version":"${{ needs.version.outputs.version }}"}}'
